MAIN=main
MAIN_LOCATION=.
PDF_LOCATION=.
USE_BIB=true
USE_IDX=true
USE_TOC=false
USE_GLO=true
GLOSSARY=glossary

include $(MYTEX_HOME)/common/make/common.mk

clean-:
	find . -name '*~' -o -name '.DS_Store' -type f | xargs rm

clean: clean-
